# User config
author: "STUDIO FOR NARRATIVE SPACES"
tagline: "RAY LC"
logo: "/assets/images/pages/SNSLogo_SDDone_01.jpg"
description: "We work with neuroscientists, roboticists, performers, designers, architects to tell immersive stories and grasp how human behaviors are shaped by environmental storytelling.<br>
Our <a href='people/'><u>members</u></a>, our <a href='pubs/'><u>publications</u></a>, and <a href='press/'><u>press</u></a> about us.<br>
Our <a href='https://raylc.org/teaching/teaching.html'><u>classes</u></a>, <a href='opportunities/'><u>opportunities</u></a> for joining us, and a <a href='residency/'><u>residency</u></a>."
keywords: "hci, installation, social good, vr ar, performance, machine learning, neuroscience, fashion tech, design fiction, games, web"
agency: "https://www.scm.cityu.edu.hk/people/ray-lc"
portfolio: "https://raylc.org"
instagram: "https://instagram.com/studiofornarrativespaces"
rednote: "https://www.xiaohongshu.com/user/profile/61f93b40000000001000cd7f?xsec_token=YB2dLzT0iJyqYA3vipJu3xDQweZpMtgNal2Taf1sY6Kjk=&xsec_source=app_share&xhsshare=CopyLink&appuid=5fad3f9c0000000001006a56&apptime=1749432531&share_id=dcadb275de074e989b64b9e53b35449c"
scholar: "https://scholar.google.com/citations?user=8wM0urcAAAAJ&hl=en"
url: "https://recfro.github.io/"
video: "930449938"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed